### ISSUE TITLE
Jar contains files it should not.

### ISSUE THREAD

**Issue by K0-RR** [gbl/EasierChests#11]
In the mod, there are files like logo.xcf and logo.png which cause the jar file to be a lot bigger (they weigh about 85% of the archive) than it should be. Also, there is another logo.xcf on the repository root that differs in size.

**Comment by gbl** [comment]
Oh right, thanks for bringing that to my attention. Fixed in the fabric 1.18 branch; if I'm updating 1.17 again I'll fix it there as well.
