### ISSUE TITLE
Search bar is rendered above MiniHUDs shulkerBoxPreview, also no option to disable it

### ISSUE THREAD

**Issue by Gorrrg** [gbl/EasierChests#7]
Hi,

I'm using the shulker box preview from masady's [MiniHUD](https://www.curseforge.com/minecraft/mc-mods/minihud) and since updating from 1.5.2 to 1.6.2 I noticed there was a search bar next to the title of inventories that gets rendered above the shulker box preview. Apparently this is a new feature in EasierChests, but there's neither an option in ModMenu nor the configuration file to disable it. The bug is quite annoying (and the feature rather useless to me at least), so I had to disable the mod.

**Comment by gbl** [comment]
You are right, EasierChests has a search bar now. I was drawing the tooltip first (which causes MiniHud to draw the shulker box preview), then the search bar. Just uploaded version 1.5.1 to CF, which changes the order of those, so the tooltip is in front of the search bar again. Should be approved in a few minutes, hopefully (https://www.curseforge.com/minecraft/mc-mods/easierchests/files/3051230)
