### ISSUE TITLE
Excessive posting to log

### ISSUE THREAD

**Issue by amyhlback** [gbl/EasierChests#8]
Using mc 1.16.3, mod version easierchests-1.16.2-fabric0.17.2-1.6.jar, every time the player inventory or a crafting bench is opened a message like this gets posted to the log roughly 10 times/second as long as the inventory is open.

`[09:07:14] [main/INFO]: [STDOUT]: handler is a class_1723`
(the number in "class_xxxx" varies)

By disabling other mods i have narrowed it down to EasierChests, and the problem still occurs with only Fabric API and EasierChests active.

**Comment by gbl** [comment]
Thanks for reporting this! I implemented this when debugging the support for the backpacks mod, then forgot to remove it when finishing the 1.6 version. Fixed in 1.6.1 which I uploaded to CF right now (can take an hour or two to become available).
