### ISSUE TITLE
Game crashes when I sort

### ISSUE THREAD

**Issue by BigBoiCheesePlatter** [gbl/EasierChests#9]
My game crashes when I try to sort either using the icon or key bind
crash log: 
[crash-2021-02-15_16.17.28-client.txt](https://github.com/gbl/EasierChests/files/5984192/crash-2021-02-15_16.17.28-client.txt)

**Comment by gbl** [comment]
You're using

Minecraft Version: 1.16.**1**

but 

easierchests: EasierChests 1.16.**5**-fabric0.30.0-1.6.3

they don't, unfortunately, work together, as there were some breaking changes in 1.16.2.

The last version that works with 1.16.1 would be https://www.curseforge.com/minecraft/mc-mods/easierchests/files/2992206.
